version: '3.8'
services:
  php:
    build: ./web
    volumes:
      - ./web:/srv/web
    environment:
      - COMPOSER_ARGS=
      - SITE_URL=http://localhost

  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - php
    volumes:
      - ./web:/srv/web
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
